config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :posts, only: [:index, :show] do
  resources :comments, only: [ :new, :create, :index ]
  end
  resources :users, only: [:show, :update, :edit] do
    resources :compliments, only: [:new, :create, :index]
  end
  resources :my_posts , only: [:new, :create, :index] do
    member do
      patch :active
      patch :done
    end
  end

 # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  resources :chatrooms, only: [:index, :new, :show, :create]
  resources :messages
end

app/controllers/my_posts_controller.rb
class MyPostsController < ApplicationController
  before_action :set_post, only: [:active, :done]
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.status = "Active"
      if @post.save
        flash[:notice] = 'Post has been saved.'
        redirect_to posts_path
      else
        render :new
      end
  end

  def index
    # if @user == current_user
    @posts = Post.all.order("created_at DESC")
    # end
  end

  def active
    @post.status = 'Active'
    @post.save
    redirect_to my_posts_path
  end

  def done
    @post.status = 'Done'
    @post.save
    redirect_to my_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :category_id, :address, :description)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/views/my_posts/index.html.erb
<div class="container">
  <div class="new-post-page">
    <div class="title">
      <h4>My posts</h4>
    </div>


    <% if current_user.posts.present? %>
    <% current_user.posts.each do |post| %>
      <div class="new-post-white-card">
      <div class="my-post-container">
        <div>
          <div class="post-title">
            <%= post.title.truncate_words(3) %>
          </div>
          <div class="post-small">
            <% elapsed_time = Time.now - post.created_at %>
            <% if Time.at(elapsed_time).utc.strftime("%e").to_i > 1 %>
            <%= Time.at(elapsed_time).utc.strftime("%e days") %>
            <% elsif Time.at(elapsed_time).utc.strftime("%k").to_i > 0 %>
            <%= Time.at(elapsed_time).utc.strftime("%k h") %> ago
            <% else %>
            <%= Time.at(elapsed_time).utc.strftime("%M mn") %> ago
            <% end %>
          </div>
        </div>
        <div>

          <% if post.status == 'Active' %>

          <!-- Button trigger modal -->
          <button type="button" class="btn btn-karma" data-toggle="modal" data-target="#Mymodal">
            Active
          </button>

          <!-- .modal -->
          <div class="modal fade" id="Mymodal">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header karma-modal-header">
                  <div class="modal-title">
                    <h4>
                    <%= post.title %>
                    </h4>
                  </div>
                </div>
                <div class="modal-creation-date">
                    <% elapsed_time = Time.now - post.created_at %>
            You created this post
            <% if Time.at(elapsed_time).utc.strftime("%e").to_i > 1 %>
            <%= Time.at(elapsed_time).utc.strftime("%e days") %>
            <% elsif Time.at(elapsed_time).utc.strftime("%k").to_i > 0 %>
            <%= Time.at(elapsed_time).utc.strftime("%k h") %> ago
            <% else %>
            <%= Time.at(elapsed_time).utc.strftime("%M mn") %> ago
            <% end %>
            </div>
            <div class="modal-description">
            <%= post.description.truncate_words(8) %>
            </div>
                <div class="modal-body karma-modal-body">
                  <div class='btn-karma'>
                    <%= link_to 'Mark as done !', done_my_post_path(post), method: :patch %>
                  </div>
                </div>
                <div class="modal-footer karma-modal-footer">
                  <button type="button" class="btn btn-default karma-modal-dismiss-button" data-dismiss="modal">
                    Close
                  </button>
<!--                   <button type="button" class="btn btn-primary">
                            Ok
                          </button> -->
                        </div>
                      </div>
                    </div>
                  </div>
                  <% elsif post.status == 'Done' %>
                  <div class="my-post-done">
                    <%= post.status %>
                  </div>
                  <% end %>


                </div>
              </div>



            </div>
            <% end %>
            <% end %>
          </div>
        </div>
      </div>

app/views/my_posts/new.html.erb
<div class="container">
  <div class="new-post-page">
    <div class="title">
      <h4>New post creation</h4>
    </div>
    <div class="new-post-white-card">
      <div class="new-post-form">
        <%= simple_form_for @post, url: my_posts_path do |f| %>
        <%= f.input :title, label: false, placeholder: "Post title", class: "post-creation-form" %>
        <%= f.association :category, label: false, prompt: "- Select a category -" %>
        <%= f.input :address, label: false, placeholder: "Where ?"%>
        <%= f.input :description, as: :text, label: 'Your message', placeholder: "Write your post here!" %>
        <div class="post-creation-buttons">
          <%#= f.submit 'Preview',  class: "btn-karma" %>
          <%= f.button :submit, class: "btn-homepage" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>