config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :posts, only: [:index, :show] do
  resources :comments, only: [ :new, :create, :index ]
  end
  resources :users, only: [:show, :update, :edit] do
    resources :compliments, only: [:new, :create, :index]
  end
  resources :my_posts , only: [:new, :create, :index] do
    member do
      patch :active
      patch :done
    end
  end

 # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  resources :chatrooms, only: [:index, :new, :show, :create]
  resources :messages
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :compliments, dependent: :destroy
  belongs_to :neighbourhood, optional: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :upload_avatar, PhotoUploader
  has_many :messages, dependent: :destroy
  has_many :chatrooms, through: :messages
  # validates :first_name, presence: true, uniqueness: true
  # validates :first_name, :last_name, :email, :upload_avatar, :personal_info, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
    @neighbourhood = @user.neighbourhood
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def edit
    redirect_to user_path(@user)
    render "show"
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :upload_avatar, :personal_info)
  end
end

app/views/users/_mypage.html.erb
<div class="userpage">
    <div class="mypage-avatar">
      <%= cl_image_tag @user.upload_avatar, crop: :thumb, gravity: :face, width: 120, height: 120, class: 'avatar-large' %>
    </div>
    <div class="mypage-username">
      <%= @user.first_name %> <%= @user.last_name %>
    </div>
    <div class="mypage-neighbourhood">
    <%= @user.neighbourhood.name %>
    </div>

    <div class="userpage-card">
       <div class="mypage-personal-info">
        "<%= @user.personal_info %>"
      </div>
      <div class="mypage-karma-points">
        You have <%= @user.karma_points %> karma points !
      </div>
      </div>
      <div class="userpage-links">
        <a class="btn-homepage" href="<%= new_my_post_path %>">Create a new post</a>
        <a class="userpage-simple-link" href="<%= my_posts_path %>">Manage my posts</a>
        <a class="userpage-simple-link" href="<%= user_path(current_user) %>">Edit my profile</a>
      </div>
    </div>
</div>

app/views/users/_userpage.html.erb
<div class="userpage">
  <div class="userpage-name-photo">
    <div>
      <%= cl_image_tag @user.upload_avatar, crop: :thumb, gravity: :face, width: 100, height: 100, class: 'avatar-square' %>
    </div>
    <div>
    <div class="userpage-username">
      <%= @user.first_name %> <%= @user.last_name %>
    </div>
    <div class="userpage-karma-points">
    <%= @user.first_name %> has <%= @user.karma_points %> karma points
    </div>
    </div>
  </div>
  <div class="userpage-personal-info">
  "<%= @user.personal_info %>"
</div>
<div class="userpage-links">
  <%= link_to new_user_compliment_path(@user) do %>
  <div class="btn-compliments">Thank <%= @user.first_name %> for the help !</div>
  <% end %>
</div>

<div class="card-container">
  <% @user.compliments.each do |compliment| %>
  <div class="compliment-card">
    "<%= compliment.text %>"
<!--     <p><%#= compliment.points %> ⭐️⭐️⭐️⭐️⭐️</p> -->
    <p><%= compliment.sender.first_name %></p>
  </div>
  <% end %>
</div>

  <!-- <a href="#" class="userpage-simple-link">Report this user</a> -->
</div>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

app/views/users/show.html.erb
<div class="container">
    <% if @user == current_user %>
    <%= render 'mypage' %>
    <% else %>
    <%= render 'userpage'%>
    <% end %>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>