config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :posts, only: [:index, :show] do
  resources :comments, only: [ :new, :create, :index ]
  end
  resources :users, only: [:show, :update, :edit] do
    resources :compliments, only: [:new, :create, :index]
  end
  resources :my_posts , only: [:new, :create, :index] do
    member do
      patch :active
      patch :done
    end
  end

 # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  resources :chatrooms, only: [:index, :new, :show, :create]
  resources :messages
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments
  validates :address, presence: true

  mount_uploader :picture, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  # STATUSES = ["Done", "Active"]
  # validates :status, inclusion: { in: STATUSES }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if params[:query].present?
      sql_query = " \
        posts.title ILIKE :query \
        OR users.first_name ILIKE :query \
        OR users.last_name ILIKE :query \
      "
      @posts = Post.joins(:user).where(sql_query, query: "%#{params[:query]}%")
    else
      @posts = Post.all.order("created_at DESC")
    end

    @posts = @posts.where.not(latitude: nil, longitude: nil)
    # @posts = Post.where.not(latitude: nil, longitude: nil)

    @markers = @posts.map do |post|
      {
        lat: post.latitude,
        lng: post.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { post: post })
      }
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.all
    @comment = @post.comments.build
     @markers =
      [{
        lat: @post.latitude,
        lng: @post.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { post: @post })
      }]
    @chatroom = Chatroom.new
  end
end

app/views/posts/_comment.html.erb
<div class="comment">
  <div class="comment-content">
    <%= comment.body %>
  </div>
  <div class="comment-small">
    by <%= comment.user.first_name %>
    <% elapsed_time = Time.now - comment.created_at %>
    -
    <% if Time.at(elapsed_time).utc.strftime("%e").to_i > 1 %>
    <%= Time.at(elapsed_time).utc.strftime("%e days") %>
    <% elsif Time.at(elapsed_time).utc.strftime("%k").to_i > 0 %>
    <%= Time.at(elapsed_time).utc.strftime("%k h") %> ago
    <% elsif Time.at(elapsed_time).utc.strftime("%M").to_i < 1 %>
    just now
    <% else %>
    <%= Time.at(elapsed_time).utc.strftime("%M mn") %> ago
    <% end %>
  </div>
</div>

app/views/posts/_infowindow.html.erb
<%= link_to post_path(post) do %><%#= link_to post_path(post) do %>
<div class="post-card">
  <div class="info-window">
    <div class="post-card-top">
<!--       <div class="post-avatar">
        <%#= cl_image_tag post.user.upload_avatar, crop: :thumb, gravity: :face, width: 40, height: 40 %>
      </div> -->
      <div class="post-header">
        <div class="post-title infowindow-title">
          <%= post.title %>
        </div>
        <div class="infowindow-title infowindow-light">
          by <%= post.user.first_name %>
          <% elapsed_time = Time.now - post.created_at %>
          - posted
            <% if Time.at(elapsed_time).utc.strftime("%e").to_i > 1 %>
            <%= Time.at(elapsed_time).utc.strftime("%e days") %>
            <% elsif Time.at(elapsed_time).utc.strftime("%k").to_i > 0 %>
            <%= Time.at(elapsed_time).utc.strftime("%k h") %> ago
            <% else %>
            <%= Time.at(elapsed_time).utc.strftime("%M mn") %> ago
          <!-- <%#= Time.at(elapsed_time).utc.strftime("%k h %Mmn") %> ago -->
          <% end %>
        </div>
      </div>
    </div>
    <div class="post-card-content">
      <div class="infowindow-post-content">
      <%= post.description.truncate_words(20) %>
      </div>
      <div class="post-small">
       - <%= post.category.name %> -
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/posts/_list.html.erb
<% @posts.each do |post| %>
  <% if post.status == "Active" %>
    <%= link_to post_path(post) do %>
      <div class="post-card" style="background-color: <%= post.category.color %>">
            <div class="post-empty">
            </div>
            <div class="post-full">
                <div class="post-avatar">
                  <%= cl_image_tag post.user.upload_avatar, crop: :thumb, gravity: :face, width: 70, height: 70, class: 'avatar-square' %>
                </div>
                <div>
                  <%= image_tag post.category.icon, class: "post-icon" %>
                </div>
              <div class="post-card-top">
                <div class="post-header">
                  <div class="post-title">
                    <%= post.title %>
                  </div>
                  <div class="post-small">
                    by <%= post.user.first_name %>
                    <% elapsed_time = Time.now - post.created_at %>
                    - posted
                    <% if Time.at(elapsed_time).utc.strftime("%e").to_i > 1 %>
                    <%= Time.at(elapsed_time).utc.strftime("%e days") %>
                    <% elsif Time.at(elapsed_time).utc.strftime("%k").to_i > 0 %>
                    <%= Time.at(elapsed_time).utc.strftime("%k h") %> ago
                    <% else %>
                    <%= Time.at(elapsed_time).utc.strftime("%M mn") %> ago
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="post-card-content">
                <div class="post-content">
                  <%= post.description %>
                </div>
             </div>
            </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/posts/_map.html.erb
<div
  id="map" class="info-window"
  style="width: 100%; height: 80vh;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  >
</div>

app/views/posts/index.html.erb
<div class="container posts-index">
  <div class="zeromargin">
    <div class="button-area">
      <div class="search-bar">
        <div class="zeromargin">
          <%= form_tag posts_path, method: :get do %>
          <%= text_field_tag :query,
          params[:query],
          class: "form-control form-control-sm search-layout",
            placeholder: "Search a post"
            %>
            <% end %>
        </div>
      </div>
      <div class="button-display">
          <a href="#map-view" data-section="#map-view" class="switch-link">Map</a>
          <a href="#list-view" data-section="#list-view" class="switch-link">List</a>
      </div>
    </div>



    <div id="list-view" class="sections">
      <%= render 'list' %>
    </div>
    <div id="map-view" class="sections display-none">
      <%= render 'map' %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
  <div class="container blue-background" style="background-color: <%= @post.category.color %>">
    <div class="white-card">

      <%= link_to user_path(@post.user) do %>
      <div class="post-user">
        <%= cl_image_tag @post.user.upload_avatar, crop: :thumb, gravity: :face, width: 100, height: 100, class: 'avatar-square' %>
      </div>
      <% end %>
      <div>
        <%= image_tag @post.category.icon, class: "post-show-icon" %>
      </div>

      <div class="show-post-header">
        <div class="show-post-title">
          <div class="show-post-h2"><h2>
            <%= @post.title %></h2>
          </div>
          <div class="show-post-small">
            by <%= @post.user.first_name %> -
            <% elapsed_time = Time.now - @post.created_at %>
            posted
            <% if Time.at(elapsed_time).utc.strftime("%e").to_i > 1 %>
            <%= Time.at(elapsed_time).utc.strftime("%e days") %>
            <% elsif Time.at(elapsed_time).utc.strftime("%k").to_i > 0 %>
            <%= Time.at(elapsed_time).utc.strftime("%k h") %> ago
            <% else %>
            <%= Time.at(elapsed_time).utc.strftime("%M mn") %> ago
            <% end %>
          </div>
          <div>
            <%= simple_form_for @chatroom, url: chatrooms_path do |f| %>
            <%= f.input :receiver_id, input_html: { value: @post.user.id }, as: :hidden  %>
            <%= f.input :topic, input_html: { value: @post.title }, as: :hidden %>
          </div>
          <div>
            <%= f.submit "Start a private chat", class: "post-conv-button" %>
          </div>
          <% end %>
        </div>
        </div>
      <div>

      <div class="show-post-content">
        <div>
          <%= @post.description %>
        </div>
      </div>



        <!-- ------map--------- -->
        <div class="post-map">
          <div
          id="map" class="info-window"
          style="width: 100%; height: 100px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
          ></div>
        </div>

          <!-- ----------end of map -->


        <div class="comment-title">Comments</div>
          <div id="comments">
            <% @comments.each do |comment| %>
            <%= render partial: "posts/comment", locals: { comment: comment } %>
            <% end %>
          </div>
        </div>

        <div class="new_comment">
          <%= render partial: 'comments/form', locals: { post: @post, comment: @comment } %>
        </div>
      </div>
    </div>
  </div>